version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: ranjithpn
      POSTGRES_PASSWORD:
